[WIP] Add vault readme
kommitters/chaincerts-smart-contracts pull request #154
Opened 2023-11-28 21:41 UTC by juanmagiraldor

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my change

2023-11-30 15:38 UTC, miguelnietoa commented on vault_contract/README.md
> +[![OSSF-Scorecard Score](https://img.shields.io/ossf-scorecard/github.com/kommitters/chaincerts-smart-contracts?label=openssf%20scorecard&style=for-the-badge)](https://api.securityscorecards.dev/proj
IMO, these badges can be removed, having them in the root README is enough.

2023-12-06 22:02 UTC, miguelnietoa requested changes
@juanmagiraldor @MarioRodriguezS comments added

2023-12-06 22:02 UTC, miguelnietoa commented on vc_issuance_contract/README.md
> +###  Example: When the VC status is valid:
Let's rename the titles
```
###  Example - VC is valid

###  Example - VC is revoked
```

2023-12-07 15:50 UTC, miguelnietoa approved these changes

2023-12-07 16:18 UTC, juanhurtado10 approved these changes

2023-12-07 16:18 UTC, merged